#!/bin/python

import math
import os
import random
import re
import sys

# Complete the dayOfProgrammer function below.
def isleapyear(year):
    if year<=1917:
        if year%4==0:
            return True
        return False
    elif year>=1919:
        if year%4==0:
            if year%100!=0 or year%400==0:
                return True
        return False
    
def dayOfProgrammer(year):
    if year==1918:
        return "26.09.1918"
    if isleapyear(year):
        return "12.09."+str(year)
    else:
        return "13.09."+str(year)

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    year = int(raw_input().strip())

    result = dayOfProgrammer(year)

    fptr.write(result + '\n')

    fptr.close()
