#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the utopianTree function below.
def utopianTree(n):
    answer=1
    if n==0:
        return 1
    if n%2==0:
        while n>0:
            answer*=2
            answer+=1
            n-=2
        return answer
    elif n%2==1:
        while n>1:
            answer*=2
            answer+=1
            n-=2
        return answer*2

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    t = int(input())

    for t_itr in range(t):
        n = int(input())

        result = utopianTree(n)

        fptr.write(str(result) + '\n')

    fptr.close()
