#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the permutationEquation function below.
def permutationEquation(p):
    mylist=[]
    for x in range(1,len(p)+1):
        for i in p:
            if x==i:
                temp=p.index(i)+1
                for j in p:
                    if temp==j:
                        mylist.append(p.index(j)+1)
    return mylist
                

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input())

    p = list(map(int, input().rstrip().split()))

    result = permutationEquation(p)

    fptr.write('\n'.join(map(str, result)))
    fptr.write('\n')

    fptr.close()
