#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'pickingNumbers' function below.
#
# The function is expected to return an INTEGER.
# The function accepts INTEGER_ARRAY a as parameter.
#

def pickingNumbers(a):
    # Write your code here
    mylist=[]
    maxi=0
    for i in a:
        templist=[]
        for j in range(len(a)):
            if 0<=i-a[j]<=1:
                templist.append(a[j])
        if len(templist)>maxi:
            mylist=templist
            maxi=len(templist)
    return len(mylist)
                

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input().strip())

    a = list(map(int, input().rstrip().split()))

    result = pickingNumbers(a)

    fptr.write(str(result) + '\n')

    fptr.close()
