#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the sockMerchant function below.
count=0
def findpair(ar):
    for i in range(len(ar)-1):
        for j in range(i+1,len(ar)):
            if ar[i]==ar[j]:
                ar.pop(j)
                ar.pop(i)
                global count
                count+=1
                return ar
    ar.pop(0)
    return ar

def sockMerchant(n, ar):
    while len(ar)>1:
        ar=findpair(ar)
    global count
    return count
        
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input())

    ar = list(map(int, input().rstrip().split()))

    result = sockMerchant(n, ar)

    fptr.write(str(result) + '\n')

    fptr.close()
