#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the staircase function below.
def staircase(n):
    space=n-1
    hash = 1
    while hash<=n:
        for i in range(0,space):
            print(end=' ')
        space-=1
        for j in range(hash):
            print('#', end='')
        hash+=1
        print()
if __name__ == '__main__':
    n = int(input())

    staircase(n)
