#!/bin/python3

import os
import sys
import math
#
# Complete the pageCount function below.
#
def pageCount(n, p):
    if p==1:
        return 0
    if n-p<p:
        if n%2==1:
            return (n-p)//2
        return math.ceil((n-p)/2)
    if n-p==p:
        return (n-p)//2
    if n-p>p:
        return p//2
    if n-p==0:
        return 0    
    #
    # Write your code here.
    #

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input())

    p = int(input())

    result = pageCount(n, p)

    fptr.write(str(result) + '\n')

    fptr.close()
