#!/bin/python

import math
import os
import random
import re
import sys

#
# Complete the 'getTotalX' function below.
#
# The function is expected to return an INTEGER.
# The function accepts following parameters:
#  1. INTEGER_ARRAY a
#  2. INTEGER_ARRAY b
#

def getTotalX(a, b):
    # Write your code here
    count=0
    lenofa=len(a)
    lenofb=len(b)
    
    for i in range(1,b[lenofb-1]+1):
        flag=0
        for j in a:
            if i%j!=0:
                flag=1
        for k in b:
            if k%i!=0:
                flag=1
        if flag==0:
            count+=1
    return count
                
        
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    first_multiple_input = raw_input().rstrip().split()

    n = int(first_multiple_input[0])

    m = int(first_multiple_input[1])

    arr = map(int, raw_input().rstrip().split())

    brr = map(int, raw_input().rstrip().split())

    total = getTotalX(arr, brr)

    fptr.write(str(total) + '\n')

    fptr.close()
