#!/bin/python

import math
import os
import random
import re
import sys

# Complete the migratoryBirds function below.
def migratoryBirds(arr):
    mydict={1:0,2:0,3:0,4:0,5:0}
    for i in arr:
        for j in mydict:
            if i==j:
                mydict.update({i:mydict[j]+1})
                break
    maxi=0
    for i in mydict:
        if mydict[i]>maxi:
            maxi=mydict[i]
    
    for i in mydict:
        if mydict[i]==maxi:
            return i
    
    
            
    
    

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    arr_count = int(raw_input().strip())

    arr = map(int, raw_input().rstrip().split())

    result = migratoryBirds(arr)

    fptr.write(str(result) + '\n')

    fptr.close()
