#!/bin/python3

import os
import sys

#
# Complete the timeConversion function below.
#
def timeConversion(s):
    #
    # Write your code here.
    a,b,c=s.split(':')
    if c[2:]=='PM':
        if a=='12':
            return str(12)+':'+b+':'+c[0:2] 
        return str(12+int(a))+':'+b+':'+c[0:2]
    elif c[2:]=='AM':
        if a=='12':
            return '00:'+b+':'+c[0:2]
        return a+':'+b+':'+c[0:2]
    #

if __name__ == '__main__':
    f = open(os.environ['OUTPUT_PATH'], 'w')

    s = input()

    result = timeConversion(s)

    f.write(result + '\n')

    f.close()
