#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the miniMaxSum function below.
def miniMaxSum(arr):
    maximum=max(arr)
    minimum=min(arr)
    addition= sum(arr)
    print((addition-maximum),(addition)-minimum)
    

if __name__ == '__main__':
    arr = list(map(int, input().rstrip().split()))

    miniMaxSum(arr)
