#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the breakingRecords function below.
def breakingRecords(scores):
    minimum=maximum=scores[0]
    maxi=mini=0
    for i in scores:
        if i>maximum:
            maximum=i
            maxi+=1
        elif i<minimum:
            minimum=i
            mini+=1
    return(maxi,mini)

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input())

    scores = list(map(int, input().rstrip().split()))

    result = breakingRecords(scores)

    fptr.write(' '.join(map(str, result)))
    fptr.write('\n')

    fptr.close()
