#!/bin/python

import math
import os
import random
import re
import sys

# Complete the beautifulDays function below.
def rev(a):
    answer=str(a)
    answer=answer[::-1]
    return int(answer)

def beautifulDays(i, j, k):
    count=0
    for a in range(i,j+1):
        if abs(a-rev(a))%k==0:
            count+=1
    return count

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    ijk = raw_input().split()

    i = int(ijk[0])

    j = int(ijk[1])

    k = int(ijk[2])

    result = beautifulDays(i, j, k)

    fptr.write(str(result) + '\n')

    fptr.close()
