#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the appendAndDelete function below.
def appendAndDelete(s, t, k):
    count=0
    for i,j in zip(s,t):
        if i==j:
            count+=1
        else:
            break
        
    total=len(s)+len(t)
    if total<=2*count+k and total%2==k%2 or total<k:
        return "Yes"
    return "No"

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    s = input()

    t = input()

    k = int(input())

    result = appendAndDelete(s, t, k)

    fptr.write(result + '\n')

    fptr.close()
